# Generated by Django 5.2.10 on 2026-01-30 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BiasharaConnectApp', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('buyer', 'Buyer'), ('seller', 'Seller')], db_index=True, editable=False, max_length=10),
        ),
    ]
