# Generated by Django 5.2.10 on 2026-02-05 11:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BiasharaConnectApp', '0003_alter_user_email_alter_user_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sellerprofile',
            old_name='location',
            new_name='business_location',
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='bio',
            field=models.TextField(blank=True, help_text='Short description about the seller or business', null=True),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
