# Generated by Django 5.2.11 on 2026-02-11 09:36

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BiasharaConnectApp', '0005_listing_listingimage_savedlisting_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingimage',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='listing_image'),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='profile_image'),
        ),
    ]
