# Generated by Django 5.2.11 on 2026-02-11 12:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BiasharaConnectApp', '0006_alter_listingimage_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listingimage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='sellerprofile',
            name='profile_image',
        ),
        migrations.AddField(
            model_name='listingimage',
            name='image_url',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='profile_image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='listingimage',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('listing',), name='unique_primary_image_per_listing'),
        ),
    ]
