# Generated by Django 5.2.11 on 2026-02-11 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BiasharaConnectApp', '0007_remove_listingimage_image_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='listingimage',
            name='unique_primary_image_per_listing',
        ),
        migrations.RenameField(
            model_name='listingimage',
            old_name='image_url',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='sellerprofile',
            old_name='profile_image_url',
            new_name='profile_image',
        ),
    ]
