# Generated by Django 5.2.11 on 2026-02-11 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BiasharaConnectApp', '0009_alter_listingimage_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingimage',
            name='image',
            field=models.ImageField(upload_to='listings/'),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='seller_profiles/'),
        ),
    ]
