# Generated by Django 5.2.11 on 2026-02-11 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BiasharaConnectApp', '0012_alter_listingimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingimage',
            name='image',
            field=models.URLField(blank=True, help_text='Cloudinary URL stored in BiasharaConnect/listing folder', null=True),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='profile_image',
            field=models.URLField(blank=True, help_text='Cloudinary URL stored in BiasharaConnect/profile_image folder', null=True),
        ),
    ]
