# Generated by Django 5.2.11 on 2026-02-11 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BiasharaConnectApp', '0014_alter_listingimage_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='condition',
            field=models.CharField(choices=[('new', 'New'), ('used', 'Used'), ('service', 'Service'), ('fresh', 'Fresh')], max_length=20),
        ),
    ]
